const mutations = {
  SET_ACCOUNT_TYPES: 'SET_ACCOUNT_TYPES',
  SET_ACCOUNTS: 'SET_ACCOUNTS',
  SET_CURRENCIES: 'SET_CURRENCIES',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_PAYMENT_TYPES: 'SET_PAYMENT_TYPES',
  SET_TRANSACTIONS: 'SET_TRANSACTIONS',
  SET_TRANSACTIONS_LISTENER: 'SET_TRANSACTIONS_LISTENER',
  SET_TRANSACTION_TYPES: 'SET_TRANSACTION_TYPES',
};
const actions = {
  FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
  FETCH_ACCOUNT_TYPES: 'FETCH_ACCOUNT_TYPES',
  FETCH_ACCOUNTS: 'FETCH_ACCOUNTS',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  FETCH_PAYMENT_TYPES: 'FETCH_PAYMENT_TYPES',
  FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
  FETCH_TRANSACTION_TYPES: 'FETCH_TRANSACTION_TYPES',
};
const getters = {
  GET_ACCOUNT_TYPES: 'GET_ACCOUNT_TYPES',
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  GET_CURRENCIES: 'GET_CURRENCIES',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PAYMENT_TYPES: 'GET_PAYMENT_TYPES',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_TRANSACTION_BY_ID: 'GET_TRANSACTION_BY_ID',
  GET_TRANSACTION_TYPES: 'GET_TRANSACTION_TYPES',
};

export const indexVuexTypes = Object.freeze({
  ...mutations,
  ...actions,
  ...getters,
});
