name: Prepare local environment
description: Prepare local environment for development by setup node, patch hosts file, and cache dependencies
runs:
  using: composite
  steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_VUE_APP_API_HTTP: http://${{ secrets.VPS_HOST }}:8081
        envkey_VUE_APP_API_VER: ${{ secrets.VUE_APP_API_VER }}
        directory: ./
        file_name: .env

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
